"use strict";
const path=require("path");
const express=require("express");
const helmet=require("helmet");
const cors=require("cors");
const config=require("./src/core/config");
const {getTenant}=require("./src/core/tenant");
const {authOptional}=require("./src/middleware/auth");
const authRouter=require("./src/modules/auth/router");
const inboxRouter=require("./src/modules/inbox/router");
const crmRouter=require("./src/modules/crm/router");
const crmToolsRouter=require("./src/modules/crm/tools-router");
const hubRouter=require("./src/modules/hub/router");
const hubPage=require("./src/modules/hub/page");
const crmPage=require("./src/modules/crm/page");
const crmToolsPage=require("./src/modules/crm/tools-page");
const crmAdminRouter=require("./src/modules/crm/admin-router");
const crmAdminPage=require("./src/modules/crm/admin-page");
const inboxPage=require("./src/modules/inbox/page");
const app=express();
app.set("trust proxy",true);
app.use(helmet({contentSecurityPolicy:false}));
app.use(cors({origin:true,credentials:false}));
app.use(express.json({limit:"2mb"}));
app.use(express.urlencoded({extended:false,limit:"2mb"}));
app.use(authOptional);
app.get("/assets/tenant-logo",(req,res)=>{const t=getTenant();if(t.branding.logoUrl)return res.redirect(302,t.branding.logoUrl);const asset=t.branding.logoAsset||"scb-logo.jpg";return res.sendFile(path.join(__dirname,"public",asset));});
app.use("/assets",express.static("public",{maxAge:0,etag:true,setHeaders:(res)=>{res.setHeader("Cache-Control","no-store, max-age=0");}}));
app.get("/favicon.ico",(req,res)=>res.redirect(302,"/assets/favicon.svg"));
app.get("/health",(req,res)=>{const t=getTenant();res.json({ok:true,service:"mrapi-hub",version:"1.5.4",tenant:t.id,brand:t.name,integrations:t.integrations,uptimeSeconds:Math.round(process.uptime())})});
app.get("/api/health",(req,res)=>{const t=getTenant();res.json({ok:true,service:"mrapi-hub",version:"1.5.4",tenant:t.id,brand:t.name,integrations:t.integrations})});
app.use("/api/auth",authRouter);
app.use("/api/inbox",inboxRouter);
app.use("/api/crm",crmRouter);
app.use("/api/crm-tools",crmToolsRouter);
app.use("/api/crm-admin",crmAdminRouter);
app.use("/api/hub",hubRouter);
app.use("/",inboxPage);
app.use("/",crmPage);
app.use("/",crmToolsPage);
app.use("/",crmAdminPage);
app.use("/",hubPage);
app.use((err,req,res,next)=>{console.error("unhandled",err);res.status(500).json({ok:false,error:"Internal error"});});
app.listen(config.port,"0.0.0.0",()=>{const t=getTenant();console.log(JSON.stringify({severity:"INFO",message:"MR API HUB started",version:"1.5.4",port:config.port,tenant:t.id,brand:t.name,crmDb:config.crmDb,inboxDb:config.inboxDb,integrations:t.integrations}))});
