"use strict";
const express=require("express");
const helmet=require("helmet");
const cors=require("cors");
const config=require("./src/core/config");
const {getTenant}=require("./src/core/tenant");
const {authOptional}=require("./src/middleware/auth");
const authRouter=require("./src/modules/auth/router");
const inboxRouter=require("./src/modules/inbox/router");
const crmRouter=require("./src/modules/crm/router");
const hubRouter=require("./src/modules/hub/router");
const hubPage=require("./src/modules/hub/page");
const crmPage=require("./src/modules/crm/page");
const inboxPage=require("./src/modules/inbox/page");
const app=express();
app.set("trust proxy",true);
app.use(helmet({contentSecurityPolicy:false}));
app.use(cors({origin:true,credentials:false}));
app.use(express.json({limit:"2mb"}));
app.use(express.urlencoded({extended:false,limit:"2mb"}));
app.use(authOptional);
app.use("/assets",express.static("public",{maxAge:0,etag:true,setHeaders:(res)=>{res.setHeader("Cache-Control","no-store, max-age=0");}}));
app.get("/favicon.ico",(req,res)=>res.redirect(302,"/assets/favicon.svg"));
app.get("/health",(req,res)=>res.json({ok:true,service:"mrapi-hub",version:"servidor-4",tenant:getTenant().id,uptimeSeconds:Math.round(process.uptime())}));
app.get("/api/health",(req,res)=>res.json({ok:true,service:"mrapi-hub",version:"servidor-4",tenant:getTenant().id}));
app.use("/api/auth",authRouter);
app.use("/api/inbox",inboxRouter);
app.use("/api/crm",crmRouter);
app.use("/api/hub",hubRouter);
app.use("/",inboxPage);
app.use("/",crmPage);
app.use("/",hubPage);
app.use((err,req,res,next)=>{console.error("unhandled",err);res.status(500).json({ok:false,error:"Internal error"});});
app.listen(config.port,"0.0.0.0",()=>console.log(JSON.stringify({severity:"INFO",message:"MR API HUB started",port:config.port,tenant:getTenant().id,crmDb:config.crmDb,inboxDb:config.inboxDb})));
