"use strict";
const express=require("express");
const {admin,crmDb}=require("../../core/google");
const {authRequired}=require("../../middleware/auth");
const {PIPELINE_STAGES,DEAL_TYPES}=require("./constants");
const {visibleOwners,canSeeOwner,canEditOwner,isAdminLike}=require("./access");
const router=express.Router();
router.use(authRequired);

const IMPORTANT_STAGES=["Nuevos Prospectos","Marca personal","Esperando PI","Para cotizar","Cotizado para enviar","Horno"];
function cleanLimit(v,d=50,max=200){return Math.max(1,Math.min(max,Number(v||d)||d));}
function ts(v){if(!v)return null;if(v.toDate)return v.toDate().toISOString();if(v instanceof Date)return v.toISOString();return String(v);}
function normDoc(doc){const d=doc.data()||{};return {id:doc.id,...d,createdAt:ts(d.createdAt),updatedAt:ts(d.updatedAt)};}
function enc(doc){if(!doc)return "";const d=doc.data()||{};const created=d.createdAt?.toDate?d.createdAt.toDate():d.createdAt;return Buffer.from(JSON.stringify({id:doc.id,createdAt:created?new Date(created).toISOString():null})).toString("base64url");}
function dec(v){try{return JSON.parse(Buffer.from(String(v||""),"base64url").toString("utf8"));}catch{return null;}}
function normStatus(v){const x=String(v||"lead").trim().toLowerCase();return ["lead","prospecto","cliente","inactivo"].includes(x)?x:"lead";}
function cleanOwner(v){return String(v||"").trim().toLowerCase();}
function todayBA(){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Argentina/Buenos_Aires",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const m={};for(const p of parts)if(p.type!=="literal")m[p.type]=p.value;return `${m.year}-${m.month}-${m.day}`;}
function addDays(iso,n){const d=new Date(`${iso}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
function rangeFor(mode,start,end){const today=todayBA();const m=String(mode||"vencidos").toLowerCase();if(m==="tareas")return {mode:m,start:"",end:"",label:"Todas las tareas"};if(m==="hoy")return {mode:m,start:today,end:today,label:"Hoy"};if(m==="manana")return {mode:m,start:addDays(today,1),end:addDays(today,1),label:"Mañana"};if(m==="semana"){const d=new Date(`${today}T12:00:00Z`),day=d.getUTCDay()||7;return {mode:m,start:addDays(today,1-day),end:addDays(today,7-day),label:"Esta semana"};}if(m==="proximos_7")return {mode:m,start:today,end:addDays(today,7),label:"Próximos 7 días"};if(m==="personalizado"&&/^\d{4}-\d{2}-\d{2}$/.test(start)&&/^\d{4}-\d{2}-\d{2}$/.test(end))return {mode:m,start,end,label:`${start} → ${end}`};return {mode:"vencidos",start:"",end:addDays(today,-1),label:"Vencidos"};}
async function ownerAllowed(user,owner){return await canSeeOwner(user,owner);}
function matchesQ(x,q){const n=String(q||"").trim().toLowerCase();if(!n)return true;return [x.title,x.name,x.contactName,x.dealTitle,x.company,x.phone,x.email,x.notes,x.owner,x.stage].join(" ").toLowerCase().includes(n);}
async function ownersMeta(user){const scope=await visibleOwners(user);if(scope===null){const s=await crmDb.collection("users").orderBy("name","asc").limit(250).get();return {owners:s.docs.map(d=>({id:d.id,name:(d.data()||{}).name||"",email:cleanOwner((d.data()||{}).email),role:(d.data()||{}).role||""})).filter(x=>x.email),reads:s.size};}return {owners:(scope||[]).map(email=>({email,name:email})),reads:0};}

router.get("/meta",async(req,res)=>{try{const m=await ownersMeta(req.authUser);res.json({ok:true,stages:PIPELINE_STAGES,dealTypes:DEAL_TYPES,importantStages:IMPORTANT_STAGES,owners:m.owners,readsEstimate:m.reads});}catch(e){res.status(500).json({ok:false,error:e.message});}});

router.get("/contacts",async(req,res)=>{
  try{
    const limit=cleanLimit(req.query.limit,25,50),status=String(req.query.status||"").trim().toLowerCase(),owner=cleanOwner(req.query.owner),cursor=dec(req.query.cursor),q=String(req.query.q||"").trim();
    const scope=await visibleOwners(req.authUser);if(owner&&scope!==null&&!scope.includes(owner))return res.status(403).json({ok:false,error:"Owner fuera de tus permisos"});
    // Sin scans: los filtros estructurados se resuelven en Firestore. La búsqueda textual se aplica sobre la página acotada.
    let query=crmDb.collection("contacts");
    if(owner)query=query.where("owner","==",owner);else if(Array.isArray(scope)&&scope.length===1)query=query.where("owner","==",scope[0]);else if(Array.isArray(scope)&&scope.length>1&&scope.length<=10)query=query.where("owner","in",scope);else if(Array.isArray(scope)&&scope.length>10)return res.status(400).json({ok:false,error:"Seleccioná un owner para listar contactos"});
    if(status)query=query.where("contactStatus","==",status);
    query=query.orderBy("createdAt","desc").orderBy(admin.firestore.FieldPath.documentId(),"desc");
    if(cursor?.createdAt&&cursor?.id)query=query.startAfter(new Date(cursor.createdAt),cursor.id);
    const snap=await query.limit(limit).get();
    let items=snap.docs.map(normDoc).filter(x=>matchesQ(x,q));
    // Enriquecer solo la página visible con hasta 10 contactId por query IN.
    const ids=items.map(x=>x.id);const dealsBy=new Map(ids.map(id=>[id,[]]));let extraReads=0;
    for(let i=0;i<ids.length;i+=10){const chunk=ids.slice(i,i+10);if(!chunk.length)continue;const ds=await crmDb.collection("deals").where("contactId","in",chunk).limit(100).get();extraReads+=ds.size;for(const d of ds.docs){const x=d.data()||{},cid=String(x.contactId||"");if(dealsBy.has(cid))dealsBy.get(cid).push({id:d.id,title:x.title||"",stage:x.stage||"",owner:x.owner||""});}}
    items=items.map(x=>({...x,contactStatus:normStatus(x.contactStatus),deals:dealsBy.get(x.id)||[],dealsCount:(dealsBy.get(x.id)||[]).length}));
    res.json({ok:true,items,nextCursor:snap.size===limit?enc(snap.docs[snap.docs.length-1]):"",hasMore:snap.size===limit,readsEstimate:snap.size+extraReads,searchNote:q?"Búsqueda aplicada sobre la página cargada; no se escaneó toda la colección.":""});
  }catch(e){console.error("tools contacts",e);res.status(500).json({ok:false,error:/index/i.test(String(e.message||""))?"Firestore requiere un índice para este filtro. No se hizo scan masivo.":e.message});}
});

router.post("/contacts",async(req,res)=>{try{const name=String(req.body?.name||"").trim();if(!name)return res.status(400).json({ok:false,error:"Nombre obligatorio"});let owner=cleanOwner(req.body?.owner||req.authUser.email);if(owner&&!(await ownerAllowed(req.authUser,owner)))return res.status(403).json({ok:false,error:"No podés asignar ese owner"});const ref=crmDb.collection("contacts").doc();await ref.set({name,company:String(req.body?.company||"").trim(),province:String(req.body?.province||"").trim(),phone:String(req.body?.phone||"").trim(),email:String(req.body?.email||"").trim(),owner,contactStatus:normStatus(req.body?.contactStatus),createdAt:new Date(),updatedAt:new Date()});res.json({ok:true,id:ref.id,writesEstimate:1,readsEstimate:0});}catch(e){res.status(500).json({ok:false,error:e.message});}});
router.put("/contacts/:id",async(req,res)=>{try{const ref=crmDb.collection("contacts").doc(req.params.id),snap=await ref.get();if(!snap.exists)return res.status(404).json({ok:false,error:"Contacto no encontrado"});const old=snap.data()||{};if(!(await canEditOwner(req.authUser,old.owner)))return res.status(403).json({ok:false,error:"Sin permiso"});const p={updatedAt:new Date()};for(const k of ["name","company","province","phone","email"])if(Object.prototype.hasOwnProperty.call(req.body||{},k))p[k]=String(req.body[k]||"").trim();if(Object.prototype.hasOwnProperty.call(req.body||{},"contactStatus"))p.contactStatus=normStatus(req.body.contactStatus);if(Object.prototype.hasOwnProperty.call(req.body||{},"owner")){const o=cleanOwner(req.body.owner);if(o&&!(await ownerAllowed(req.authUser,o)))return res.status(403).json({ok:false,error:"No podés asignar ese owner"});p.owner=o;}await ref.update(p);res.json({ok:true,readsEstimate:1,writesEstimate:1});}catch(e){res.status(500).json({ok:false,error:e.message});}});

router.post("/deals",async(req,res)=>{try{const title=String(req.body?.title||"").trim(),contactId=String(req.body?.contactId||"").trim();if(!title||!contactId)return res.status(400).json({ok:false,error:"Contacto y título son obligatorios"});const cs=await crmDb.collection("contacts").doc(contactId).get();if(!cs.exists)return res.status(404).json({ok:false,error:"Contacto no encontrado"});const contact=cs.data()||{};if(!(await canEditOwner(req.authUser,contact.owner)))return res.status(403).json({ok:false,error:"Sin permiso"});const stage=PIPELINE_STAGES.includes(req.body?.stage)?req.body.stage:"No responde";const owner=cleanOwner(req.body?.owner||contact.owner||req.authUser.email);if(owner&&!(await ownerAllowed(req.authUser,owner)))return res.status(403).json({ok:false,error:"No podés asignar ese owner"});const ref=crmDb.collection("deals").doc();await ref.set({title,contactId,contactName:contact.name||"",company:contact.company||"",value:Number(req.body?.value||0)||0,dueDate:String(req.body?.dueDate||"").slice(0,10),stage,dealType:DEAL_TYPES.includes(req.body?.dealType)?req.body.dealType:"LCL_PROPIO",owner,notes:String(req.body?.notes||"").trim(),files:[],createdAt:new Date(),updatedAt:new Date()});res.json({ok:true,id:ref.id,readsEstimate:1,writesEstimate:1});}catch(e){res.status(500).json({ok:false,error:e.message});}});

router.get("/agenda/items",async(req,res)=>{
  try{
    const limit=cleanLimit(req.query.limit,150,200),range=rangeFor(req.query.mode,req.query.start,req.query.end),owner=cleanOwner(req.query.owner),stage=String(req.query.stage||"important"),taskStatus=String(req.query.taskStatus||"pending"),itemType=String(req.query.itemType||"all"),q=String(req.query.q||"").trim();
    const scope=await visibleOwners(req.authUser);if(owner&&scope!==null&&!scope.includes(owner))return res.status(403).json({ok:false,error:"Owner fuera de tus permisos"});const ownerPass=o=>{const x=cleanOwner(o);if(owner)return x===owner;if(scope===null)return true;return scope.includes(x);};const stagePass=s=>stage==="all"||!stage?true:stage==="important"?IMPORTANT_STAGES.includes(String(s||"")):String(s||"")===stage;
    const items=[];let reads=0;
    if(itemType!=="deals"){
      let tq=crmDb.collection("tasks");if(range.mode==="tareas")tq=tq.orderBy("taskDate","desc");else if(range.mode==="vencidos")tq=tq.where("taskDate","<",todayBA()).orderBy("taskDate","desc");else tq=tq.where("taskDate",">=",range.start).where("taskDate","<=",range.end).orderBy("taskDate","asc");const snap=await tq.limit(limit).get();reads+=snap.size;for(const d of snap.docs){const x=d.data()||{},status=String(x.status||"pending").toLowerCase();if(!ownerPass(x.owner))continue;if(taskStatus!=="all"&&status!==taskStatus)continue;if(range.mode!=="tareas"&&!stagePass(x.stage))continue;const it={type:"task",taskId:d.id,date:String(x.taskDate||""),time:String(x.taskTime||""),title:x.title||"Tarea",notes:x.notes||"",status,contactId:x.contactId||"",contactName:x.contactName||"",dealId:x.dealId||"",dealTitle:x.dealTitle||"",stage:x.stage||"",owner:x.owner||""};if(matchesQ(it,q))items.push(it);}
    }
    if(itemType!=="tasks"&&range.mode!=="tareas"){
      let dq=crmDb.collection("deals");if(range.mode==="vencidos")dq=dq.where("dueDate","<",todayBA()).orderBy("dueDate","desc");else dq=dq.where("dueDate",">=",range.start).where("dueDate","<=",range.end).orderBy("dueDate","asc");const snap=await dq.limit(limit).get();reads+=snap.size;for(const d of snap.docs){const x=d.data()||{};if(!ownerPass(x.owner)||!stagePass(x.stage))continue;const it={type:"deal",dealId:d.id,date:String(x.dueDate||""),time:"",title:x.title||"Trato",notes:x.notes||"",contactId:x.contactId||"",contactName:x.contactName||"",dealTitle:x.title||"",stage:x.stage||"",owner:x.owner||""};if(matchesQ(it,q))items.push(it);}
    }
    // Relación tarea ↔ vencimiento dentro de la misma página, sin reads extra.
    const taskByDeal=new Map(items.filter(x=>x.type==="task"&&x.dealId).map(x=>[x.dealId,x]));for(const it of items)if(it.type==="deal"&&taskByDeal.has(it.dealId)){const t=taskByDeal.get(it.dealId);it.relatedTaskId=t.taskId;it.relatedTaskTitle=t.title;it.relatedTaskNotes=t.notes;}
    const today=todayBA();const urgency=x=>x.date<today?0:x.date===today?1:x.date===addDays(today,1)?2:3;items.sort((a,b)=>urgency(a)-urgency(b)||String(a.date).localeCompare(String(b.date))||(a.type==="task"?-1:1)||String(a.time||"99:99").localeCompare(String(b.time||"99:99")));
    const out=items.slice(0,limit),summary={total:out.length,tasks:out.filter(x=>x.type==="task").length,deals:out.filter(x=>x.type==="deal").length,overdue:out.filter(x=>x.date<today).length,today:out.filter(x=>x.date===today).length,tomorrow:out.filter(x=>x.date===addDays(today,1)).length};
    res.json({ok:true,items:out,summary,rangeLabel:range.label,readsEstimate:reads});
  }catch(e){console.error("agenda items",e);res.status(500).json({ok:false,error:/index/i.test(String(e.message||""))?"Firestore requiere un índice para este rango. No se hizo scan masivo.":e.message});}
});

router.post("/tasks",async(req,res)=>{try{const contactId=String(req.body?.contactId||"").trim(),dealId=String(req.body?.dealId||"").trim(),title=String(req.body?.title||"").trim(),taskDate=String(req.body?.taskDate||"").slice(0,10);if(!contactId||!dealId||!title||!/^\d{4}-\d{2}-\d{2}$/.test(taskDate))return res.status(400).json({ok:false,error:"Contacto, trato, título y fecha son obligatorios"});const [cs,ds]=await Promise.all([crmDb.collection("contacts").doc(contactId).get(),crmDb.collection("deals").doc(dealId).get()]);if(!cs.exists||!ds.exists)return res.status(404).json({ok:false,error:"Contacto o trato no encontrado"});const c=cs.data()||{},d=ds.data()||{};if(!(await canEditOwner(req.authUser,d.owner)))return res.status(403).json({ok:false,error:"Sin permiso"});const ref=crmDb.collection("tasks").doc();await ref.set({contactId,contactName:c.name||d.contactName||"",dealId,dealTitle:d.title||"",stage:d.stage||"",owner:d.owner||c.owner||req.authUser.email||"",title,taskDate,taskTime:String(req.body?.taskTime||"").slice(0,5),notes:String(req.body?.notes||"").trim(),status:"pending",createdBy:req.authUser.email||req.authUser.id,createdAt:new Date(),updatedAt:new Date()});res.json({ok:true,id:ref.id,readsEstimate:2,writesEstimate:1});}catch(e){res.status(500).json({ok:false,error:e.message});}});
router.put("/tasks/:id",async(req,res)=>{try{const ref=crmDb.collection("tasks").doc(req.params.id),snap=await ref.get();if(!snap.exists)return res.status(404).json({ok:false,error:"Tarea no encontrada"});const x=snap.data()||{};if(!(await canEditOwner(req.authUser,x.owner)))return res.status(403).json({ok:false,error:"Sin permiso"});const p={updatedAt:new Date()};for(const k of ["title","taskDate","taskTime","notes"])if(Object.prototype.hasOwnProperty.call(req.body||{},k))p[k]=String(req.body[k]||"").trim();if(Object.prototype.hasOwnProperty.call(req.body||{},"status")){const s=String(req.body.status||"").toLowerCase();if(!["pending","done","cancelled"].includes(s))return res.status(400).json({ok:false,error:"Estado inválido"});p.status=s;if(s==="done")p.completedAt=new Date();}await ref.update(p);res.json({ok:true,readsEstimate:1,writesEstimate:1});}catch(e){res.status(500).json({ok:false,error:e.message});}});
router.delete("/tasks/:id",async(req,res)=>{try{const ref=crmDb.collection("tasks").doc(req.params.id),snap=await ref.get();if(!snap.exists)return res.status(404).json({ok:false,error:"Tarea no encontrada"});if(!(await canEditOwner(req.authUser,(snap.data()||{}).owner)))return res.status(403).json({ok:false,error:"Sin permiso"});await ref.delete();res.json({ok:true,readsEstimate:1,writesEstimate:1});}catch(e){res.status(500).json({ok:false,error:e.message});}});

module.exports=router;
